
ignoredBuiltDependencies: [ "@prisma/engines", "core-js", "esbuild", "prisma", "sharp" ]
minimumReleaseAge: 1440
overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
  h3@>=2.0.0-0 <2.0.1-rc.15: '>=2.0.1-rc.15'
  h3@>=2.0.0-beta.0 <=2.0.0-rc.8: '>=2.0.1-rc.9'
  h3@>=2.0.0-beta.0 <=2.0.1-rc.16: '>=2.0.1-rc.17'
  h3@>=2.0.0-beta.4 <2.0.1-rc.18: '>=2.0.1-rc.18'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'
  srvx@<0.11.13: '>=0.11.13'
