/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AdminRouteRouteImport } from './pages/admin/route'
import { Route as CurriculumDotpdfRouteImport } from './pages/curriculum[.]pdf'
import { Route as AdminIndexRouteImport } from './pages/admin/index'
import { Route as AuthPathRouteImport } from './pages/auth/$path'
import { Route as ApiAdminExportProfileDotyamlRouteImport } from './pages/api/admin/export-profile[.]yaml'
import { Route as ApiAuthSplatRouteImport } from './pages/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumDotpdfRoute = CurriculumDotpdfRouteImport.update({
  id: '/curriculum.pdf',
  path: '/curriculum.pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminExportProfileDotyamlRoute =
  ApiAdminExportProfileDotyamlRouteImport.update({
    id: '/api/admin/export-profile.yaml',
    path: '/api/admin/export-profile.yaml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/curriculum.pdf': typeof CurriculumDotpdfRoute
  '/auth/$path': typeof AuthPathRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/export-profile.yaml': typeof ApiAdminExportProfileDotyamlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curriculum.pdf': typeof CurriculumDotpdfRoute
  '/auth/$path': typeof AuthPathRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/export-profile.yaml': typeof ApiAdminExportProfileDotyamlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/curriculum.pdf': typeof CurriculumDotpdfRoute
  '/auth/$path': typeof AuthPathRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/export-profile.yaml': typeof ApiAdminExportProfileDotyamlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/curriculum.pdf'
    | '/auth/$path'
    | '/admin/'
    | '/api/admin/export-profile.yaml'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/curriculum.pdf'
    | '/auth/$path'
    | '/admin'
    | '/api/admin/export-profile.yaml'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/curriculum.pdf'
    | '/auth/$path'
    | '/admin/'
    | '/api/admin/export-profile.yaml'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CurriculumDotpdfRoute: typeof CurriculumDotpdfRoute
  AuthPathRoute: typeof AuthPathRoute
  ApiAdminExportProfileDotyamlRoute: typeof ApiAdminExportProfileDotyamlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum.pdf': {
      id: '/curriculum.pdf'
      path: '/curriculum.pdf'
      fullPath: '/curriculum.pdf'
      preLoaderRoute: typeof CurriculumDotpdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/export-profile.yaml': {
      id: '/api/admin/export-profile.yaml'
      path: '/api/admin/export-profile.yaml'
      fullPath: '/api/admin/export-profile.yaml'
      preLoaderRoute: typeof ApiAdminExportProfileDotyamlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CurriculumDotpdfRoute: CurriculumDotpdfRoute,
  AuthPathRoute: AuthPathRoute,
  ApiAdminExportProfileDotyamlRoute: ApiAdminExportProfileDotyamlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
